/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.NoHubMethod.NoHubMethodAnswerMessage */
export type NoHubMethodAnswerMessage = {
    /** Transpiled from string */
    correlationId: string;
}

