/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.TwoSubscription.TwoSubscriptionRequestMessage */
export type TwoSubscriptionRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
}

/** Transpiled from BE01.IntegrationTest.Scenarios.TwoSubscription.TwoSubscriptionResponseMessage */
export type TwoSubscriptionResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
}

