/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.OnConnection.OnConnectionStatusModel */
export type OnConnectionStatusModel = {
    /** Transpiled from bool */
    isConnected: boolean;
}

