/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.SimpleDateTimeField.SimpleDateTimeRequestMessage */
export type SimpleDateTimeRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
    /** Transpiled from System.DateTime */
    paramDateTime: (Date | string);
}

/** Transpiled from BE01.IntegrationTest.Scenarios.SimpleDateTimeField.SimpleDateTimeResponseMessage */
export type SimpleDateTimeResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
    /** Transpiled from System.DateTime */
    paramDateTime: (Date | string);
}

