/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.Simple.SimpleRequestMessage */
export type SimpleRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
}

/** Transpiled from BE01.IntegrationTest.Scenarios.Simple.SimpleResponseMessage */
export type SimpleResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
}

