/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.SimpleContext.SimpleContexRequestMessage */
export type SimpleContexRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
}

/** Transpiled from BE01.IntegrationTest.Scenarios.SimpleContext.SimpleContexResponseMessage */
export type SimpleContexResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
    /** Transpiled from string */
    connectionId: string;
}

