/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.SimpleContext.SimpleContextRequestMessage */
export type SimpleContextRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
}

/** Transpiled from BE01.IntegrationTest.Scenarios.SimpleContext.SimpleContextResponseMessage */
export type SimpleContextResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
    /** Transpiled from string */
    connectionId: string;
}

