/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.ConnectionIdSender.InfoModel */
export type InfoModel = {
    /** Transpiled from string? */
    connectionId?: string;
}

