/* 
 * Auto-generated TypeScript File by UiRtc
 * Version: 1.0.
 * Generated on: 2025-02-09 00:24:19 UTC 
 * Do not modify this file manually.
 */
/* eslint-disable */
/* tslint:disable */

import {
  HubConnection,
  HubConnectionBuilder,
  HubConnectionState
} from "@microsoft/signalr";

type uiRtcHubs = 'AttributeDeclaration' | 'SimpleHub' | 'TwoContractsHub';
const allHubs: uiRtcHubs[] = ['AttributeDeclaration', 'SimpleHub', 'TwoContractsHub'];

type hubMethods = AttributeDeclarationMethod | SimpleHubMethod | TwoContractsHubMethod;

type AttributeDeclarationMethod = 'AttributeDeclarationAttributeHandler';
type SimpleHubMethod = 'SimpleHandler';
type TwoContractsHubMethod = 'TwoContracts';

type hubSubscriptions = AttributeDeclarationSubscription | SimpleHubSubscription | TwoContractsHubSubscription;

type AttributeDeclarationSubscription = 'AttributeDeclarationAttributeAnswer';
type SimpleHubSubscription = 'SimpleAnswer';
type TwoContractsHubSubscription = 'TwoContractsAnswer1' | 'TwoContractsAnswer2';

const connections: RConnections = {
    AttributeDeclaration: {},
  SimpleHub: {},
  TwoContractsHub: {},
};

export const uiRtcSubscription = {
    AttributeDeclaration: {
    AttributeDeclarationAttributeAnswer: (callBack: (data: AttributeDeclarationResponseMessage) => void) => subscribe("AttributeDeclaration", "AttributeDeclarationAttributeAnswer", callBack),
  },
  SimpleHub: {
    SimpleAnswer: (callBack: (data: SimpleResponseMessage) => void) => subscribe("SimpleHub", "SimpleAnswer", callBack),
  },
  TwoContractsHub: {
    TwoContractsAnswer1: (callBack: (data: TwoContractsResponseMessage) => void) => subscribe("TwoContractsHub", "TwoContractsAnswer1", callBack),
    TwoContractsAnswer2: (callBack: (data: TwoContractsResponseMessage) => void) => subscribe("TwoContractsHub", "TwoContractsAnswer2", callBack),
  },

};

export const uiRtcCommunication = {
    AttributeDeclaration: {
    AttributeDeclarationAttributeHandler: (request: AttributeDeclarationRequestMessage) => send("AttributeDeclaration", "AttributeDeclarationAttributeHandler", request),
  },
  SimpleHub: {
    SimpleHandler: (request: SimpleRequestMessage) => send("SimpleHub", "SimpleHandler", request),
  },
  TwoContractsHub: {
    TwoContracts: (request: TwoContractsRequestMessage) => send("TwoContractsHub", "TwoContracts", request),
  },

};

/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.AttributeDeclaration.AttributeDeclarationRequestMessage */
export type AttributeDeclarationRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
}

/** Transpiled from BE01.IntegrationTest.Scenarios.AttributeDeclaration.AttributeDeclarationResponseMessage */
export type AttributeDeclarationResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
}



/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.Simple.SimpleRequestMessage */
export type SimpleRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
}

/** Transpiled from BE01.IntegrationTest.Scenarios.Simple.SimpleResponseMessage */
export type SimpleResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
}



/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from BE01.IntegrationTest.Scenarios.TwoHubsTwoContracts.TwoContractsRequestMessage */
export type TwoContractsRequestMessage = {
    /** Transpiled from string */
    correlationId: string;
}

/** Transpiled from BE01.IntegrationTest.Scenarios.TwoHubsTwoContracts.TwoContractsResponseMessage */
export type TwoContractsResponseMessage = {
    /** Transpiled from string */
    correlationId: string;
}



/* Hard code */
export interface IUiRtcConfiguration {
  serverUrl: string;
  activeHubs: uiRtcHubs[] | "All";
}

interface IHub {
  connection?: HubConnection;
}

type RConnections = Record<uiRtcHubs, IHub>;

export const uiRtc = {
  init: async (config: IUiRtcConfiguration) => {
    const hubsToInitialize =
      config.activeHubs === "All" ? allHubs : config.activeHubs;
    hubsToInitialize.forEach((hub) => initHub(config.serverUrl, hub));
  },
  dispose: (hubs: uiRtcHubs[] | "All" | undefined) => {
    const hubsToInitialize =
      hubs === "All" || hubs === undefined ? allHubs : hubs;
    hubsToInitialize.forEach((hub) => disposeHub(hub));
  },
};

const initHub = async (serverUrl: string, hubName: uiRtcHubs) => {
  if (!!connections[hubName].connection) {
    console.warn(hubName + " hub has been initialized already");
    return;
  }

  try {
    connections[hubName].connection = buildConnection(serverUrl + hubName);
    await connections[hubName].connection.start();
  } catch (err) {
    console.error(
      "Error while establishing connection '" + hubName + "': ",
      err
    );
  }
};

const buildConnection = (url: string) => {
  let builder = new HubConnectionBuilder();
  builder.withUrl(url);
  builder.withAutomaticReconnect();

  return builder.build();
};

const disposeHub = (hubName: uiRtcHubs) => {
  if (
    !!connections[hubName].connection &&
    (connections[hubName].connection.state === HubConnectionState.Connected ||
      connections[hubName].connection.state === HubConnectionState.Connecting ||
      connections[hubName].connection.state === HubConnectionState.Reconnecting)
  ) {
    try {
      connections[hubName].connection.stop();
    } catch (err) {
      console.error(
        "Error while establishing connection '" + hubName + "': ",
        err
      );
    }
  } else {
    console.warn(hubName + " hub has not been initialized");
  }
};

const subscribe = (
  hub: uiRtcHubs,
  sub: hubSubscriptions,
  callBack: (data: any) => void
) => {
  connections[hub].connection?.on(sub, callBack);
};

const send = (hub: uiRtcHubs, method: hubMethods, request?: any) => {
  if (!!request) {
    connections[hub].connection?.send(method, request);
  } else {
    connections[hub].connection?.send(method);
  }
};