/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from AuthenticatedAccessTokenFactoryExample.Backend.Communication.Models.ChatMessageRequest */
export type ChatMessageRequest = {
    /** Transpiled from string */
    message: string;
}

/** Transpiled from AuthenticatedAccessTokenFactoryExample.Backend.Communication.Models.ChatMessageResponse */
export type ChatMessageResponse = {
    /** Transpiled from string */
    message: string;
    /** Transpiled from string */
    userId: string;
    /** Transpiled from string */
    userName: string;
    /** Transpiled from string */
    connectionId: string;
    /** Transpiled from System.DateTime */
    sentAtUtc: (Date | string);
}
